# Generated by Django 2.1.7 on 2019-03-25 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='发布时间'),
            preserve_default=False,
        ),
    ]
