# Generated by Django 2.1.7 on 2019-05-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default='摘要', max_length=300, verbose_name='摘要'),
            preserve_default=False,
        ),
    ]
