# Generated by Django 2.1.7 on 2019-10-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='slogan',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='上传图片'),
        ),
    ]
